import { StyleSheet } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#00BCD4',
  },
  header: {
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    backgroundColor: '#00BCD4',
  },
  backButton: {
    alignSelf: 'flex-start',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    marginBottom: spacing.md,
  },
  backButtonText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.semibold,
  },
  headerTitle: {
    fontSize: typography.sizes.h1,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  scrollContent: {
    flex: 1,
  },
  summaryContainer: {
    backgroundColor: '#F5F7FA',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxl,
    minHeight: '100%',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    marginBottom: spacing.lg,
  },
  summaryIcon: {
    fontSize: 28,
    marginRight: spacing.sm,
  },
  summaryTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  teacherSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5F7',
    marginHorizontal: spacing.xl,
    padding: spacing.lg,
    borderRadius: 15,
    marginBottom: spacing.lg,
    borderLeftWidth: 4,
    borderLeftColor: '#00BCD4',
  },
  teacherAvatar: {
    width: 60,
    height: 60,
    backgroundColor: colors.white,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  teacherAvatarEmoji: {
    fontSize: 32,
  },
  teacherInfo: {
    flex: 1,
  },
  teacherName: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  teacherCourse: {
    fontSize: typography.sizes.small,
    color: '#00BCD4',
    fontWeight: typography.weights.semibold,
  },
  infoSection: {
    marginHorizontal: spacing.xl,
    marginBottom: spacing.lg,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  infoIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  infoTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  modalityBadge: {
    backgroundColor: '#FF6B35',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: spacing.md,
  },
  modalityBadgeText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    textTransform: 'lowercase',
  },
  locationInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    padding: spacing.md,
    borderRadius: 10,
  },
  locationIcon: {
    fontSize: 18,
    marginRight: spacing.sm,
    marginTop: 2,
  },
  locationText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  platformInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: spacing.md,
    borderRadius: 10,
  },
  platformIcon: {
    fontSize: 18,
    marginRight: spacing.sm,
  },
  platformText: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
  },
  timeSlotsContainer: {
    gap: spacing.sm,
  },
  timeSlotItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    padding: spacing.md,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#FFEB3B',
  },
  timeSlotIcon: {
    fontSize: 20,
    marginRight: spacing.md,
  },
  timeSlotInfo: {
    flex: 1,
  },
  timeSlotDay: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  timeSlotDetails: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timeSlotTime: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
  },
  totalHours: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  totalHoursLabel: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
    marginRight: spacing.sm,
  },
  totalHoursValue: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    color: '#FF6B35',
  },
  descriptionBox: {
    backgroundColor: '#F5F5F5',
    padding: spacing.md,
    borderRadius: 10,
  },
  descriptionText: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  costSection: {
    marginHorizontal: spacing.xl,
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 15,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  costHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: '#FFEB3B',
  },
  costIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  costTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  costItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  costLabel: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
  },
  costValue: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.semibold,
    color: colors.text.primary,
  },
  costSubtext: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
    marginBottom: spacing.md,
  },
  costDivider: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: spacing.md,
  },
  totalCost: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  totalCostLabel: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  totalCostValue: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: '#FF6B35',
  },
  paymentSection: {
    marginHorizontal: spacing.xl,
    marginBottom: spacing.xl,
  },
  paymentInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    padding: spacing.md,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#FFEB3B',
  },
  paymentIcon: {
    fontSize: 24,
    marginRight: spacing.md,
  },
  paymentText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  confirmContainer: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    paddingBottom: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 10,
  },
  confirmButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B35',
    paddingVertical: spacing.lg,
    borderRadius: 25,
    marginBottom: spacing.sm,
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  confirmButtonText: {
    color: colors.white,
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
  },
  termsText: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 18,
  },
});