import { StyleSheet, Dimensions } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    backgroundColor: '#00BCD4',
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    fontSize: 28,
    marginRight: spacing.xs,
  },
  logoText: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  notificationButton: {
    width: 44,
    height: 44,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  notificationIcon: {
    fontSize: 24,
  },
  notificationBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#FF4444',
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: typography.weights.bold,
  },
  userButton: {
    width: 44,
    height: 44,
    backgroundColor: colors.white,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  userAvatar: {
    fontSize: 24,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 25,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  searchInput: {
    flex: 1,
    paddingVertical: spacing.md,
    fontSize: typography.sizes.body,
    color: colors.text.primary,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  filterButtonIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  filterButtonText: {
    color: '#00BCD4',
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.semibold,
  },
  filterBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#FF4444',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: typography.weights.bold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userMenu: {
    backgroundColor: colors.white,
    borderRadius: 15,
    width: width * 0.85,
    maxWidth: 350,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    overflow: 'hidden',
  },
  userMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    backgroundColor: '#00BCD4',
  },
  userMenuAvatar: {
    fontSize: 48,
    marginRight: spacing.md,
  },
  userMenuInfo: {
    flex: 1,
  },
  userMenuName: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  userMenuEmail: {
    fontSize: typography.sizes.small,
    color: colors.white,
    opacity: 0.9,
  },
  userMenuDivider: {
    height: 1,
    backgroundColor: colors.border,
  },
  userMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    paddingHorizontal: spacing.xl,
  },
  userMenuIcon: {
    fontSize: 24,
    marginRight: spacing.md,
    width: 30,
  },
  userMenuText: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    fontWeight: typography.weights.medium,
  },
  logoutItem: {
    backgroundColor: '#FFF5F5',
  },
  logoutText: {
    color: '#FF4444',
    fontWeight: typography.weights.semibold,
  },
  filterModalFullScreen: {
    flex: 1,
    backgroundColor: colors.white,
    paddingTop: spacing.xxl,
  },
  filterModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    borderBottomWidth: 2,
    borderBottomColor: '#00BCD4',
    backgroundColor: '#E0F7FA',
  },
  filterModalTitle: {
    fontSize: typography.sizes.h1,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  filterModalCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterModalClose: {
    fontSize: 24,
    color: colors.text.primary,
    fontWeight: typography.weights.bold,
  },
  filterModalContent: {
    flex: 1,
    padding: spacing.xl,
  },
  filterSection: {
    marginBottom: spacing.xxl,
  },
  filterSectionTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: '#00BCD4',
    marginBottom: spacing.sm,
  },
  filterSectionSubtitle: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
    marginBottom: spacing.lg,
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: colors.white,
    minWidth: 120,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  filterOptionSelected: {
    backgroundColor: '#00BCD4',
    borderColor: '#00BCD4',
    shadowColor: '#00BCD4',
    shadowOpacity: 0.3,
    elevation: 5,
  },
  filterOptionIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  filterOptionText: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    fontWeight: typography.weights.medium,
  },
  filterOptionTextSelected: {
    color: colors.white,
    fontWeight: typography.weights.bold,
  },
  filterModalFooter: {
    flexDirection: 'row',
    padding: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: spacing.md,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
  },
  filterClearButton: {
    flex: 1,
    paddingVertical: spacing.lg,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#00BCD4',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  filterClearButtonText: {
    color: '#00BCD4',
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
  },
  filterApplyButton: {
    flex: 2,
    paddingVertical: spacing.lg,
    borderRadius: 25,
    backgroundColor: '#00BCD4',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#00BCD4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  filterApplyButtonText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.xxl,
  },
  section: {
    paddingTop: spacing.xl,
    paddingBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
  },
  teachersList: {
    paddingHorizontal: spacing.lg,
  },
  teacherCardWrapper: {
    width: width * 0.8,
    marginRight: spacing.md,
  },
  teacherCard: {
    backgroundColor: '#FFF9E6',
    borderRadius: 20,
    padding: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  teacherImageContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  teacherImage: {
    fontSize: 56,
  },
  teacherInfo: {
    alignItems: 'center',
  },
  teacherName: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  teacherSubject: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  teacherModality: {
    fontSize: typography.sizes.body,
    color: '#00BCD4',
    fontWeight: typography.weights.semibold,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 20,
  },
  ratingStar: {
    fontSize: 18,
    marginRight: spacing.xs,
  },
  ratingValue: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginRight: spacing.xs,
  },
  ratingReviews: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
  },
});