import { StyleSheet, Dimensions } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#00BCD4',
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: 24,
    color: colors.white,
    fontWeight: typography.weights.bold,
  },
  headerTitle: {
    fontSize: typography.sizes.h1,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  headerRight: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teacherAvatar: {
    fontSize: 32,
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#FFE082',
  },
  infoBannerIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  infoBannerText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.primary,
  },
  scrollContent: {
    flex: 1,
  },
  calendarHeaderContainer: {
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  weekButton: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E0F7FA',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#00BCD4',
    shadowColor: '#00BCD4',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  weekButtonIcon: {
    fontSize: 24,
    color: '#00BCD4',
    fontWeight: typography.weights.bold,
  },
  weekButtonDisabled: {
    color: '#B0BEC5',
    opacity: 0.5,
  },
  weekDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00BCD4',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 25,
    marginHorizontal: spacing.sm,
    flex: 1,
    maxWidth: 200,
    justifyContent: 'center',
    shadowColor: '#00BCD4',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  weekIcon: {
    fontSize: 20,
    marginRight: spacing.xs,
  },
  weekText: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  weekIndicator: {
    alignItems: 'center',
    paddingVertical: spacing.sm,
    backgroundColor: '#F5F5F5',
  },
  weekIndicatorText: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    fontWeight: typography.weights.medium,
  },
  calendarContainer: {
    backgroundColor: colors.white,
    paddingVertical: spacing.md,
  },
  calendarRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  timeColumn: {
    width: 80,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    borderRightWidth: 2,
    borderRightColor: '#E0E0E0',
    paddingVertical: spacing.sm,
  },
  columnHeader: {
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  timeText: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    fontWeight: typography.weights.medium,
  },
  dayColumn: {
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.sm,
    backgroundColor: '#FAFAFA',
  },
  dayName: {
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  dayDate: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
  },
  timeSlot: {
    width: 100,
    height: 50,
    borderRightWidth: 1,
    borderRightColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  timeSlotSelected: {
    backgroundColor: '#00BCD4',
  },
  checkmark: {
    fontSize: 24,
    color: colors.white,
    fontWeight: typography.weights.bold,
  },
  bottomInfoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    padding: spacing.md,
    marginTop: spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#FFE082',
  },
  bottomInfoIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  bottomInfoText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.primary,
  },
  section: {
    padding: spacing.xl,
  },
  sectionTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.lg,
  },
  label: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.semibold,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  coursesGrid: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  courseOption: {
    flex: 1,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  courseOptionSelected: {
    backgroundColor: '#FFEB3B',
    borderColor: '#FFEB3B',
  },
  courseOptionText: {
    fontSize: typography.sizes.small,
    color: colors.text.primary,
    fontWeight: typography.weights.medium,
    textAlign: 'center',
  },
  courseOptionTextSelected: {
    color: colors.text.primary,
    fontWeight: typography.weights.bold,
  },
  textArea: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.md,
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  modalityGrid: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  modalityOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: colors.white,
  },
  modalityOptionSelected: {
    backgroundColor: '#FFEB3B',
    borderColor: '#FFEB3B',
  },
  modalityIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  modalityText: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    fontWeight: typography.weights.semibold,
  },
  modalityTextSelected: {
    fontWeight: typography.weights.bold,
  },
  platformsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  platformOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: colors.white,
    minWidth: '47%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  platformOptionSelected: {
    backgroundColor: '#E0F7FA',
    borderColor: '#00BCD4',
    borderWidth: 3,
    shadowColor: '#00BCD4',
    shadowOpacity: 0.2,
    elevation: 5,
  },
  platformIcon: {
    fontSize: 28,
    marginRight: spacing.sm,
  },
  platformText: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    fontWeight: typography.weights.medium,
  },
  platformTextSelected: {
    color: '#00BCD4',
    fontWeight: typography.weights.bold,
  },
  locationOption: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: spacing.lg,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    backgroundColor: colors.white,
    marginBottom: spacing.md,
  },
  locationOptionTeacher: {
    backgroundColor: '#E0F7FA',
    borderColor: '#00BCD4',
  },
  locationOptionSelected: {
    borderColor: '#00BCD4',
    borderWidth: 3,
  },
  locationRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#00BCD4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    marginTop: spacing.xs,
  },
  locationRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#00BCD4',
  },
  locationContent: {
    flex: 1,
  },
  locationLabel: {
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.bold,
    color: '#00BCD4',
    marginBottom: spacing.xs,
  },
  locationAddress: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  mapSection: {
    marginTop: spacing.lg,
    padding: spacing.lg,
    backgroundColor: '#00BCD4',
    borderRadius: 15,
  },
  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  mapIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  mapTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  mapAddress: {
    fontSize: typography.sizes.small,
    color: colors.white,
    marginBottom: spacing.md,
    lineHeight: 20,
  },
  mapContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: spacing.xl,
    alignItems: 'center',
    minHeight: 150,
  },
  mapEmoji: {
    fontSize: 50,
    marginBottom: spacing.md,
  },
  mapText: {
    fontSize: typography.sizes.body,
    color: colors.white,
    marginBottom: spacing.md,
  },
  mapButton: {
    backgroundColor: colors.white,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
  },
  mapButtonText: {
    color: '#00BCD4',
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.semibold,
  },
  actionButtons: {
    flexDirection: 'row',
    padding: spacing.lg,
    gap: spacing.md,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  returnButton: {
    flex: 1,
    paddingVertical: spacing.md,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#FF5722',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF5722',
  },
  returnButtonText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
  },
  cartButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    borderRadius: 25,
    backgroundColor: '#FFEB3B',
    shadowColor: '#FFEB3B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  cartButtonIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  cartButtonText: {
    color: colors.text.primary,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
  },
});