import { StyleSheet, Dimensions } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  heroSection: {
    backgroundColor: '#FF8A65',
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.xl,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  backButtonText: {
    fontSize: 24,
    color: colors.white,
    fontWeight: typography.weights.bold,
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroLeft: {
    marginRight: spacing.lg,
  },
  avatarLarge: {
    width: 150,
    height: 150,
    backgroundColor: '#FFF3E0',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  avatarEmoji: {
    fontSize: 80,
  },
  imageGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  imageGridItem: {
    width: 72,
    height: 72,
    backgroundColor: '#FFF3E0',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageGridEmoji: {
    fontSize: 32,
  },
  heroRight: {
    flex: 1,
  },
  teacherName: {
    fontSize: typography.sizes.h1,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginBottom: spacing.xs,
  },
  teacherSubject: {
    fontSize: typography.sizes.body,
    color: 'rgba(255, 255, 255, 0.95)',
    marginBottom: spacing.md,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  stars: {
    flexDirection: 'row',
    marginRight: spacing.xs,
  },
  star: {
    fontSize: 16,
  },
  ratingNumber: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginRight: spacing.xs,
  },
  ratingReviews: {
    fontSize: typography.sizes.small,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  modalityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  modalityIcon: {
    fontSize: 16,
    marginRight: spacing.xs,
  },
  modalityText: {
    color: colors.white,
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.semibold,
  },
  actionButtons: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00BCD4',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.sm,
    borderRadius: 15,
    shadowColor: '#00BCD4',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  actionButtonSecondary: {
    backgroundColor: '#FFEB3B',
    shadowColor: '#FFEB3B',
  },
  actionButtonTertiary: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: '#00BCD4',
    shadowColor: '#000',
    shadowOpacity: 0.1,
  },
  actionButtonIcon: {
    fontSize: 18,
    marginRight: spacing.xs,
  },
  actionButtonText: {
    color: colors.white,
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.bold,
    textAlign: 'center',
  },
  actionButtonTextSecondary: {
    color: '#000',
  },
  actionButtonTextTertiary: {
    color: '#00BCD4',
  },
  scrollContent: {
    flex: 1,
  },
  section: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
  },
  sectionTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.lg,
  },
  videoContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 15,
    padding: spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  videoPlaceholder: {
    fontSize: 60,
    marginBottom: spacing.md,
  },
  videoText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    marginBottom: spacing.lg,
  },
  playButton: {
    backgroundColor: '#FF4444',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xl,
    borderRadius: 25,
  },
  playButtonText: {
    color: colors.white,
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
  },
  priceInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    padding: spacing.md,
    borderRadius: 12,
    marginBottom: spacing.lg,
    borderLeftWidth: 4,
    borderLeftColor: '#FF9800',
  },
  priceIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  priceText: {
    flex: 1,
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    fontWeight: typography.weights.semibold,
  },
  coursesCarousel: {
    gap: spacing.md,
  },
  courseCard: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  courseTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  courseDetails: {
    gap: spacing.sm,
  },
  courseDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  courseDetailIcon: {
    fontSize: 18,
    marginRight: spacing.sm,
  },
  courseDetailText: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
  },
  carouselDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E0E0E0',
  },
  dotActive: {
    width: 24,
    backgroundColor: '#00BCD4',
  },
  addressCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 15,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  addressIcon: {
    fontSize: 32,
    marginRight: spacing.md,
  },
  addressContent: {
    flex: 1,
  },
  addressLabel: {
    fontSize: typography.sizes.small,
    color: '#00BCD4',
    fontWeight: typography.weights.bold,
    marginBottom: spacing.xs,
  },
  addressText: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    lineHeight: 22,
  },
  mapContainer: {
    backgroundColor: '#E0F7FA',
    borderRadius: 15,
    padding: spacing.xxl,
    alignItems: 'center',
    marginBottom: spacing.md,
    minHeight: 200,
  },
  mapEmoji: {
    fontSize: 60,
    marginBottom: spacing.md,
  },
  mapText: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
    marginBottom: spacing.lg,
  },
  mapButton: {
    backgroundColor: '#00BCD4',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: 20,
  },
  mapButtonText: {
    color: colors.white,
    fontSize: typography.sizes.small,
    fontWeight: typography.weights.semibold,
  },
  infoBox: {
    flexDirection: 'row',
    backgroundColor: '#E3F2FD',
    padding: spacing.lg,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#2196F3',
  },
  infoIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  infoText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  ratingOverview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    padding: spacing.xl,
    borderRadius: 15,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 3,
  },
  ratingBig: {
    fontSize: 60,
    fontWeight: typography.weights.bold,
    color: '#00BCD4',
    marginRight: spacing.lg,
  },
  ratingOverviewRight: {
    flex: 1,
  },
  starsLarge: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  recommendationText: {
    fontSize: typography.sizes.body,
    color: colors.text.secondary,
  },
  reviewsGrid: {
    gap: spacing.md,
  },
  reviewCard: {
    backgroundColor: '#00BCD4',
    padding: spacing.lg,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  reviewAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  reviewAvatarEmoji: {
    fontSize: 28,
  },
  reviewHeaderInfo: {
    flex: 1,
  },
  reviewName: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    color: colors.white,
  },
  reviewDate: {
    fontSize: typography.sizes.small,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  reviewStars: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  reviewComment: {
    fontSize: typography.sizes.small,
    color: colors.white,
    lineHeight: 20,
  },
});