import { StyleSheet } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  header: {
    backgroundColor: '#00BCD4',
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 25,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  logoIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  logoText: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  headerTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: typography.sizes.body,
    color: colors.white,
    textAlign: 'center',
    opacity: 0.95,
    paddingHorizontal: spacing.md,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.xxl,
  },
  form: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  section: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  mainTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  mainSubtitle: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  tipsSection: {
    backgroundColor: '#FFF9E6',
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: '#FFD700',
  },
  tipsTitle: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  tipItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.sm,
  },
  tipIcon: {
    color: '#FFD700',
    fontSize: 16,
    marginRight: spacing.sm,
    marginTop: 2,
  },
  tipText: {
    flex: 1,
    fontSize: typography.sizes.small,
    color: colors.text.primary,
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  sectionTitleIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  required: {
    color: colors.error,
  },
  scheduleHeader: {
    flexDirection: 'row',
    backgroundColor: '#00BCD4',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  scheduleRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderLeftColor: colors.border,
    borderRightColor: colors.border,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  dayColumn: {
    width: 80,
    paddingHorizontal: spacing.sm,
  },
  dayName: {
    fontSize: typography.sizes.body,
    fontWeight: typography.weights.semibold,
    color: colors.text.primary,
  },
  timeSlotColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
  },
  timeSlotIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  timeSlotName: {
    fontSize: typography.sizes.tiny,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginBottom: 2,
  },
  timeSlotTime: {
    fontSize: typography.sizes.tiny - 2,
    color: colors.white,
    opacity: 0.9,
  },
  allDayColumn: {
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  allDayText: {
    fontSize: typography.sizes.tiny,
    fontWeight: typography.weights.bold,
    color: colors.white,
    textAlign: 'center',
  },
  checkbox: {
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#00BCD4',
    borderColor: '#00BCD4',
  },
  checkmark: {
    color: colors.white,
    fontSize: 18,
    fontWeight: typography.weights.bold,
  },
  allDayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  allDayButtonSelected: {
    backgroundColor: '#00BCD4',
    borderColor: '#00BCD4',
  },
  allDayButtonText: {
    fontSize: 24,
    color: colors.text.secondary,
    fontWeight: typography.weights.bold,
  },
  allDayButtonTextSelected: {
    color: colors.white,
  },
  hint: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
    marginTop: -spacing.sm,
    marginBottom: spacing.md,
    fontStyle: 'italic',
  },
  errorText: {
    color: colors.error,
    fontSize: typography.sizes.small,
    marginTop: spacing.sm,
  },
  summarySection: {
    backgroundColor: '#E0F7FA',
    borderRadius: 12,
    padding: spacing.lg,
    borderWidth: 2,
    borderColor: '#00BCD4',
  },
  summaryTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  summaryIcon: {
    fontSize: 20,
    marginRight: spacing.sm,
  },
  summaryGrid: {
    gap: spacing.sm,
  },
  summaryCard: {
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: spacing.md,
    alignItems: 'center',
    borderLeftWidth: 4,
    borderLeftColor: '#00BCD4',
  },
  summaryCardIcon: {
    fontSize: 32,
    marginBottom: spacing.xs,
  },
  summaryCardLabel: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  summaryCardValue: {
    fontSize: typography.sizes.body,
    color: '#00BCD4',
    fontWeight: typography.weights.bold,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  cancelButton: {
    flex: 1,
  },
  nextButton: {
    flex: 1,
  },
});