import { StyleSheet } from 'react-native';
import colors from '../../styles/colors';
import typography from '../../styles/typography';
import spacing from '../../styles/spacing';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  header: {
    backgroundColor: '#00BCD4',
    paddingTop: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: 25,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  logoIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  logoText: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  headerTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.white,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: typography.sizes.body,
    color: colors.white,
    textAlign: 'center',
    opacity: 0.95,
    paddingHorizontal: spacing.md,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing.xxl,
  },
  form: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
  },
  section: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  mainTitle: {
    fontSize: typography.sizes.h2,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  mainSubtitle: {
    fontSize: typography.sizes.small,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  successBanner: {
    backgroundColor: '#D4EDDA',
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: '#28A745',
    alignItems: 'center',
  },
  successIcon: {
    fontSize: 48,
    marginBottom: spacing.md,
  },
  successTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: '#155724',
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  successText: {
    fontSize: typography.sizes.body,
    color: '#155724',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.sm,
  },
  successSubtext: {
    fontSize: typography.sizes.small,
    color: '#155724',
    textAlign: 'center',
    lineHeight: 20,
    fontStyle: 'italic',
  },
  reviewSection: {
    backgroundColor: colors.white,
    borderRadius: 12,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: '#00BCD4',
    overflow: 'hidden',
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: '#00BCD4',
  },
  reviewIcon: {
    fontSize: 24,
    marginRight: spacing.sm,
  },
  reviewTitle: {
    fontSize: typography.sizes.h3,
    fontWeight: typography.weights.bold,
    color: colors.text.primary,
  },
  reviewContent: {
    padding: spacing.md,
    backgroundColor: '#F8F9FA',
  },
  reviewRow: {
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  reviewLabel: {
    fontSize: typography.sizes.tiny,
    color: colors.text.secondary,
    fontWeight: typography.weights.semibold,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  reviewValue: {
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    lineHeight: 20,
  },
  reviewValueSuccess: {
    fontSize: typography.sizes.body,
    color: '#28A745',
    lineHeight: 20,
  },
  termsSection: {
    backgroundColor: '#FFF9E6',
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
    marginTop: 2,
  },
  checkboxSelected: {
    backgroundColor: '#00BCD4',
    borderColor: '#00BCD4',
  },
  checkmark: {
    color: colors.white,
    fontSize: 16,
    fontWeight: typography.weights.bold,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: typography.sizes.body,
    color: colors.text.primary,
    lineHeight: 22,
  },
  link: {
    color: '#00BCD4',
    fontWeight: typography.weights.semibold,
    textDecorationLine: 'underline',
  },
  required: {
    color: colors.error,
  },
  errorText: {
    color: colors.error,
    fontSize: typography.sizes.small,
    marginTop: -spacing.sm,
    marginBottom: spacing.sm,
    marginLeft: 32,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  cancelButton: {
    flex: 1,
  },
  submitButton: {
    flex: 2,
  },
});